if file is a block special file --> [ -b $file ]
if file is a character special file --> [ -c $file ]
check if file is a directory --> [ -d $file ]
if file is an ordinary file --> [ -f $file ]
check if file has a set of group id  bit set --> [ -g $file ]
check if file has strickly bit set --> [ -k $file ]
check if file is named pipe --> [ -p $file ]
check if file descriptor is open associated with a terminal --> [ -t $file ]
if file has its set user id --> [ -u $file ]
check file is readable --> [ -r $file ]
check file is writeable --> [ -w $file ]
check file is executable --> [ -x $file ]
check file size is greater than 0 --> [ -s $file ]
check if file exist --> [ -e $file ]