equality of variables --> [ $a -eq $b ]
not equal --> [ $a -ne $b ]
greater than --> [ $a -gt $b ]
less than --> [ $a -lt $b ]
greater than equal to --> [ $a -ge $b ]
less than equal to --> [ $a -le $b ]
